### PR TITLE
fix: force https connection, automatic trailing slash, catch error

### LINKED ISSUE #16: Catch fetch error when connection fails

### LINKED ISSUE #17: Encode url
To accept # in password

### LINKED ISSUE #18: Always use https
Graasp won't accept http connection.

- Add if not exists
- error on http
- ...

Handle trailing `/` automatically.

### PR DESCRIPTION
**Pull request by pyphilia**
I addressed 3 (4) issues in this PR

- force https for base url close #18 
- catch error when connection is failing close #16 
- encode url to handle special caracters close #17 
- remove trailing / automatically

Additionally I translated most strings.

Since I don't have a server to connect to for tests, don't hesitate to check that everything is still working!

### CODE REVIEW

File: src/components/modes/teacher/Settings.js [hunk 1]
```diff
@@ -141,33 +142,45 @@ class Settings extends Component {
...
 
+    // apiEndpoint must be https
+    if (!apiEndpoint.startsWith(DEFAULT_PROTOCOL)) {
+      return this.setState({
+        connectionUserHint: t(UNEXPECTED_ENDPOINT_PROTOCOL_MESSAGE),
+        connectionEstablished: false,
+      });
+    }
+
+    // add trailing / to endpoint
```
Comment (juancarlosfarah) [inline src/components/modes/teacher/Settings.js:153]: `// remove...`

**Review by juancarlosfarah — CHANGES_REQUESTED** [review]
Just a very minor comment in a comment. Otherwise all good.

**Review by juancarlosfarah — CHANGES_REQUESTED** [review]
This all looks good, but I see some tests failing, which means that there is probably something that broke with the new interface.

**Comment by juancarlosfarah** [comment]
These are the tests that are failing.

image
